In [2]:
for i in range(10,1):
    print(i)

In [3]:
import numpy as np
a=np.arange(1,10)
print(a[::-1])

[9 8 7 6 5 4 3 2 1]


In [10]:
a=np.arange(1,2**3+1)
a=np.reshape(a,(2,2,2))
print("a",a.T)
b=np.arange(1,3)
b=np.reshape(b,(2,1))
print("b",b)
print(np.dot(a,b))

a [[[1 5]
  [3 7]]

 [[2 6]
  [4 8]]]
b [[1]
 [2]]
[[[ 5]
  [11]]

 [[17]
  [23]]]
